name: macOS build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        project: [ binutils, gcc-7 ]
        target: [ m68k-atari-mint, m68k-atari-mintelf ]
        include:
          - project: binutils
            version: 2.41
            source_archive: https://ftp.gnu.org/gnu/binutils/binutils-2.41.tar.xz
          - project: gcc-7
            version: 7.5.0
            source_archive: https://ftp.gnu.org/gnu/gcc/gcc-7.5.0/gcc-7.5.0.tar.xz
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH keys
        if: ${{ github.event_name == 'push' }}
        env:
          SSH_ID: ${{ secrets.SSH_ID }}
        run: ./.scripts/install_ssh_id.sh
      - name: Install packages
        run: wget -nv ${{ matrix.source_archive }}
      - name: build
        env:
          BUILD_ARM64: yes
        run: ./.scripts/build-wrap.sh ${{ matrix.project }} ${{ matrix.target }}
      - name: deploy
        if: ${{ github.event_name == 'push' }}
        env:
          COMMITER_NAME: ${{ github.event.commits[0].author.name }}
          COMMITER_EMAIL: ${{ github.event.commits[0].author.email }}
          PROJECT_NAME: ${{ matrix.project }}
          PROJECT_VERSION: ${{ matrix.version }}
          TARGET: ${{ matrix.target }}
        run: ./.scripts/deploy.sh
